name: Generate Animation

on:
  # Schedule the workflow to run every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # Allow manual workflow dispatch
  workflow_dispatch:
  
  # Trigger workflow on every push to the master branch
  push:
    branches:
      - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the GitHub contribution snake animation SVGs
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: zzhrachel
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=blue
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue
          
      # Push SVGs to output branch for GitHub Pages display
      - name: Deploy GitHub Contribution Snake SVG
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

